name: "Unit Test"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "16"

permissions:
  contents: write
  pull-requests: write

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run test
        run: npm run test:coverage
